#!/bin/bash

rm -rf /tmp/hugo_cache/
hugo mod graph
npm install -D autoprefixer
npm install -D postcss-cli
npm install

#npm install -D postcss
#cd themes/docsy && git submodule update -f --init && cd ../..
